kernel_settings_sysctl:
  - name: net.ipv4.tcp_rmem
    value: "4096 87380 16777216"
  - name: net.ipv4.tcp_wmem
    value: "4096 16384 16777216"
  - name: net.ipv4.udp_mem
    value: "3145728 4194304 16777216"
  - name: net.ipv4.conf.default.secure_redirects
    value: '0'
  - name: net.ipv6.conf.all.accept_source_route
    value: '0'

kernel_settings_sysfs:
  - name: /sys/kernel/debug/x86/pti_enabled
    value: 0
  - name: /sys/kernel/debug/x86/retp_enabled
    value: 0
  - name: /sys/kernel/debug/x86/ibrs_enabled
    value: 0

crypto_policies_policy: "DEFAULT:NO-SHA1"
crypto_policies_reload: true

# set kdump_path to NFS mounted drive
#kdump_path: /share

# session recording for all users
tlog_scope_sssd: all

firewall:
  - port: '44321/tcp'
    state: enabled
  - port: '514/tcp'
    state: enabled
  - port: '20514/tcp'
    state: enabled

timesync_ntp_servers:
  - hostname: clock.corp.redhat.com
    iburst: yes
    maxpoll: 10

logging_inputs:
  - name: system_input
    type: basics
logging_outputs:
  - name: relp_client
    type: relp
    target: "{{ logging_server }}"
    tls: true
    ca_cert: /etc/pki/ca-trust/source/anchors/demo-ca.crt
    cert: /etc/pki/tls/certs/{{ inventory_hostname }}.crt
    private_key: /etc/pki/tls/private/{{ inventory_hostname }}.key
    permitted_servers:
      - "*.{{ logging_domain }}"
logging_flows:
  - name: flow
    inputs: [system_input]
    outputs: [relp_client]
